name: ✨Feature Request
description: Request a new feature or enhancement
labels: ["enhancement"]
title: "[FEAT]: "
body:
  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if a relevant feature request already exists.
      options:
      - label: I have searched the existing feature requests
        required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a brief description of the feature or enhancement you would like
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the feature request like proposed solutions, links, screenshots, etc.

